---
# tasks file for ansible-role-workstation-bootstrap

- name: Install packages
  apt:
    name: "{{ item.name }}"
    state: latest
  with_items: "{{ workstation_bootstrap_packages }}"


# Create a 2048-bit SSH key for user jsmith in ~jsmith/.ssh/id_rsa
- user:
    name: "{{ workstation_bootstrap_username }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

